/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Blue_Corals: THREE.Mesh;
  };
  materials: {
    ["Blue Corals"]: THREE.MeshStandardMaterial;
  };
};

export default function CoralModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/corals.glb") as GLTFResult;
  return (
    <group {...props} scale={0.7} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Blue_Corals.geometry}
        material={materials["Blue Corals"]}
        position={[0.006, -0.006, -0.602]}
        scale={[0.688, 0.521, 0.688]}
      />
    </group>
  );
}

useGLTF.preload("/models/corals.glb");
